### ISSUE TITLE
Styleguide is generated but without any style

### ISSUE THREAD

**Issue by ethyde** [Documented-Style-Sheets/grunt-dss#21]
Hi ! :)
I have a question about how to use this grunt plugin : when i generated the styleguide, everything work but there is no style applied to.
In the less file : 

``` less
//
// @name Button
// @description Your standard form button.
//
// @state :hover - Highlights when hovering.
// @state :disabled - Dims the button when disabled.
// @state .primary - Indicates button is the primary action.
// @state .smaller - A smaller button
//
// @markup
// <button>This is a button</button>
//
button {
  padding: 5px 15px;
  line-height: normal;
  font-family: "Helvetica Neue", Helvetica;
  font-size: 12px;
  font-weight: bold;
  color: #666;
  text-shadow: 0 1px rgba(255, 255, 255, 0.9);
  border-radius: 3px;
  border: 1px solid #ddd;
  border-bottom-color: #bbb;
  background: #f5f5f5;
  filter: progid:DXImageTransform.Microsoft.gradient(GradientType=0, startColorstr='$start', endColorstr='$end');
  background: -webkit-gradient(linear, left top, left bottom, from(#f5f5f5), to(#e5e5e5));
  background: -moz-linear-gradient(top, #f5f5f5, #e5e5e5);
  box-shadow: 0 1px 4px rgba(0, 0, 0, 0.15);
  cursor: pointer;
}
```

My grunt task whas : 

```
dss: {
    docs: {
        files: {
            '<%= meta.filesRoute.doc %>/styleguide/dist/': ['<%= meta.filesRoute.less %>/base.less']
        }
    }
}
```

and the result in the console : 

```
Running "dss:docs" (dss) task
✓ Styleguide overwrited at: src/Bundle/FrontendBundle/Resources/doc/styleguide/dist/

Done, without errors.
```

But result styleguide : 
![2014-04-20_123956](https://cloud.githubusercontent.com/assets/409987/2750428/2d9c28b0-c878-11e3-8b87-76a360c9b416.png)

Thanks for your help !
